<a href="https://colab.research.google.com/github/ludawg44/jigsawlabs/blob/master/17Apr20_Holdout%20Sets%20Lab_v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Holdout Sets Lab

### Introduction

In this lesson, we'll see how we can use holdout sets to correct for overfitting.  We'll do so, with the use of one of the datasets built into sklearn, the california housing dataset.

### Loading our Data

Let's begin by loading our dataset from sklearn.

In [0]:
from sklearn.datasets import fetch_california_housing
dataset = fetch_california_housing()

Now the `fetch_california_housing` method returns to us a dictionary like object.  Begin by viewing the keys in our dataset.

In [0]:
# LV
type(dataset)

sklearn.utils.Bunch

In [0]:
# LV
dataset

{'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 20640\n\n    :Number of Attributes: 8 numeric, predictive attributes and the target\n\n    :Attribute Information:\n        - MedInc        median income in block\n        - HouseAge      median house age in block\n        - AveRooms      average number of rooms\n        - AveBedrms     average number of bedrooms\n        - Population    block population\n        - AveOccup      average house occupancy\n        - Latitude      house block latitude\n        - Longitude     house block longitude\n\n    :Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttp://lib.stat.cmu.edu/datasets/\n\nThe target variable is the median house value for California districts.\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geograp

In [0]:
# LV: `dict.keys()` method returns a dictionary view obejct, which acts as a set. 
# Iterating over the dictionary directly also yeilds keys, so turning a dictionary
# into a list results in a list of all the keys. 

dict_keys = dataset.keys()
dict_keys
# dict_keys(['data', 'target', 'feature_names', 'DESCR'])

dict_keys(['data', 'target', 'feature_names', 'DESCR'])

One of the keys is `DESCR`.  This is the description of the dataset.  Let's print out the first 1000 lines of the description.

In [0]:
# print DESCR here
dataset.DESCR.split('\n')

['.. _california_housing_dataset:',
 '',
 'California Housing dataset',
 '--------------------------',
 '',
 '**Data Set Characteristics:**',
 '',
 '    :Number of Instances: 20640',
 '',
 '    :Number of Attributes: 8 numeric, predictive attributes and the target',
 '',
 '    :Attribute Information:',
 '        - MedInc        median income in block',
 '        - HouseAge      median house age in block',
 '        - AveRooms      average number of rooms',
 '        - AveBedrms     average number of bedrooms',
 '        - Population    block population',
 '        - AveOccup      average house occupancy',
 '        - Latitude      house block latitude',
 '        - Longitude     house block longitude',
 '',
 '    :Missing Attribute Values: None',
 '',
 'This dataset was obtained from the StatLib repository.',
 'http://lib.stat.cmu.edu/datasets/',
 '',
 'The target variable is the median house value for California districts.',
 '',
 'This dataset was derived from the 1990 U.S. census, u

Ok, now that we have a sense of the data, let's gather our features.  Create a dataframe from the `dataset` in the `data` key, and name the columns the list of names in the `feature_names` from the dataset.  Assign the dataframe to the variable `X`.

In [0]:
# LV https://scikit-learn.org/stable/auto_examples/inspection/plot_partial_dependence.html#sphx-glr-auto-examples-inspection-plot-partial-dependence-py

import numpy as np
import pandas as pd

X = pd.DataFrame(dataset.data, columns = dataset.feature_names)
X.head()

MedInc  HouseAge  AveRooms  ...  AveOccup  Latitude  Longitude
0  8.3252      41.0  6.984127  ...  2.555556     37.88    -122.23
1  8.3014      21.0  6.238137  ...  2.109842     37.86    -122.22
2  7.2574      52.0  8.288136  ...  2.802260     37.85    -122.24
3  5.6431      52.0  5.817352  ...  2.547945     37.85    -122.25
4  3.8462      52.0  6.281853  ...  2.181467     37.85    -122.25

[5 rows x 8 columns]

In [0]:
X[:3]

# 	MedInc	HouseAge	AveRooms	AveBedrms	Population	AveOccup	Latitude	Longitude
# 0	8.3252	41.0	6.984127	1.023810	322.0	2.555556	37.88	-122.23
# 1	8.3014	21.0	6.238137	0.971880	2401.0	2.109842	37.86	-122.22
# 2	7.2574	52.0	8.288136	1.073446	496.0	2.802260	37.85	-122.24

MedInc  HouseAge  AveRooms  ...  AveOccup  Latitude  Longitude
0  8.3252      41.0  6.984127  ...  2.555556     37.88    -122.23
1  8.3014      21.0  6.238137  ...  2.109842     37.86    -122.22
2  7.2574      52.0  8.288136  ...  2.802260     37.85    -122.24

[3 rows x 8 columns]

Retrieve the target data from the dataset, and store the data in a pandas series.  Assign it to the variable `y`.

In [0]:
# https://note.nkmk.me/en/python-pandas-list/

y = pd.Series(dataset.target)

In [0]:
type(y)
# pandas.core.series.Series

pandas.core.series.Series

In [0]:
y[:3]
# 0    4.526
# 1    3.585
# 2    3.521
# dtype: float64

0    4.526
1    3.585
2    3.521
dtype: float64

Ok, now that we have separate our features and targets, let's train a linear regression model.

In [0]:
from sklearn.linear_model import LinearRegression

model = LinearRegression().fit(X, y)
model

# LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

> And calculate the score on the linear regression model.

In [0]:
model.score(X, y)
# 0.6062326851998051

0.6062326851998049

### Checking for Overfitting

Let's take a look at the coefficients from our previous model.

In [0]:
model.coef_
# array([ 4.36693293e-01,  9.43577803e-03, -1.07322041e-01,  6.45065694e-01,
#        -3.97638942e-06, -3.78654265e-03, -4.21314378e-01, -4.34513755e-01])

array([ 4.36693293e-01,  9.43577803e-03, -1.07322041e-01,  6.45065694e-01,
       -3.97638942e-06, -3.78654265e-03, -4.21314378e-01, -4.34513755e-01])

There is one for each of the columns.  So one *crude* way to get a sense of what features may not be contributing too much is to sort our columns by the size of the associated coefficients, from largest to smallest.

> We'll improve on this technique for feature importance in future lessons.

Use numpy to do it.  Assign the result to `sorted_cols`.

In [0]:
X.columns

Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude'],
      dtype='object')

In [0]:
stacked_coef= np.stack([model.coef_, X.columns], axis=1)
stacked_coef

array([[0.4366932931343245, 'MedInc'],
       [0.009435778033237972, 'HouseAge'],
       [-0.10732204139090447, 'AveRooms'],
       [0.645065693519812, 'AveBedrms'],
       [-3.976389421211576e-06, 'Population'],
       [-0.003786542654971, 'AveOccup'],
       [-0.42131437752714385, 'Latitude'],
       [-0.43451375467477743, 'Longitude']], dtype=object)

In [0]:
arg_order = np.flip(np.argsort(stacked_coef[:,0]))


In [0]:
sorted_feature = stacked_coef[arg_order]

In [0]:
sorted_cols = sorted_feature[:,1].astype('<U10')
sorted_cols
# array(['AveBedrms', 'MedInc', 'HouseAge', 'Population', 'AveOccup',
#        'AveRooms', 'Latitude', 'Longitude'], dtype='<U10')

array(['AveBedrms', 'MedInc', 'HouseAge', 'Population', 'AveOccup',
       'AveRooms', 'Latitude', 'Longitude'], dtype='<U10')

Ok, now this will be our plan.  We'll create eight different datasets.  The first one will only have the feature `AveBedrms`, then the next one will have the features `AveBedrms` and `MedInc`, then the next dataset will add on `HouseAge`, and so on.

Use list comprehension to create a list of 8 dataframes, each one with an additional feature.

In [0]:
sorted_cols[0:0]

array([], dtype='<U10')

In [0]:
feature_datasets = [X[cols] for cols in [sorted_cols[0:i] for i in range(1, 9)]]

In [0]:
feature_datasets

[       AveBedrms
 0       1.023810
 1       0.971880
 2       1.073446
 3       1.073059
 4       1.081081
 ...          ...
 20635   1.133333
 20636   1.315789
 20637   1.120092
 20638   1.171920
 20639   1.162264
 
 [20640 rows x 1 columns],        AveBedrms  MedInc
 0       1.023810  8.3252
 1       0.971880  8.3014
 2       1.073446  7.2574
 3       1.073059  5.6431
 4       1.081081  3.8462
 ...          ...     ...
 20635   1.133333  1.5603
 20636   1.315789  2.5568
 20637   1.120092  1.7000
 20638   1.171920  1.8672
 20639   1.162264  2.3886
 
 [20640 rows x 2 columns],        AveBedrms  MedInc  HouseAge
 0       1.023810  8.3252      41.0
 1       0.971880  8.3014      21.0
 2       1.073446  7.2574      52.0
 3       1.073059  5.6431      52.0
 4       1.081081  3.8462      52.0
 ...          ...     ...       ...
 20635   1.133333  1.5603      25.0
 20636   1.315789  2.5568      18.0
 20637   1.120092  1.7000      17.0
 20638   1.171920  1.8672      18.0
 20639   1.162264  2

In [0]:
len(feature_datasets)
# 8

8

In [0]:
feature_datasets[0][:3]
# 	AveBedrms
# 0	1.023810
# 1	0.971880
# 2	1.073446

AveBedrms
0   1.023810
1   0.971880
2   1.073446

In [0]:
feature_datasets[1][:3]
# 	AveBedrms	MedInc
# 0	1.023810	8.3252
# 1	0.971880	8.3014
# 2	1.073446	7.2574

AveBedrms  MedInc
0   1.023810  8.3252
1   0.971880  8.3014
2   1.073446  7.2574

Ok, now that we have our eight different datasets, we'll use our train each of these datasets on the first `4/5` of the data, and allocate the remaining 20 percent for the test set.

For example, here's how we could do this with just our first dataset.

In [0]:
training_cutoff = np.int(.8*X.shape[0])
training_cutoff
# 16512.0

16512

In [0]:
LinearRegression().fit(X[:training_cutoff], y[:training_cutoff])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

> Now use list comprehension to loop through each of the feature datasets and train each model.

In [0]:
models = [LinearRegression().fit(feature_dataset[:training_cutoff], y[:training_cutoff]) for feature_dataset in feature_datasets]
models
# models

[LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False),
 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False),
 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False),
 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False),
 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False),
 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False),
 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False),
 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)]

Confirm that you did this correctly by taking a look at the coefficients of your models.  There should be only one coefficient in the first model (as you trained on one feature, and two on the second, and so on.

In [0]:
[model.coef_ for model in models]

# [array([-0.08472077]),
#  array([-0.00530241,  0.4078728 ]),
#  array([0.03627788, 0.42396549, 0.01832752]),
#  array([4.41398935e-02, 4.24895746e-01, 1.93896280e-02, 3.70981852e-05]),
#  array([ 4.39572800e-02,  4.24936826e-01,  1.95360434e-02,  4.09593233e-05,
#         -1.21859740e-02]),
#  array([ 1.05174649e+00,  5.36219341e-01,  1.73618921e-02,  2.53744473e-05,
#         -1.17657007e-02, -2.21649954e-01]),
#  array([ 9.71711856e-01,  5.21567608e-01,  1.76671678e-02,  1.93844117e-05,
#         -1.17596405e-02, -2.01479564e-01, -3.98712430e-02]),
#  array([ 7.10267788e-01,  4.47847084e-01,  9.40820722e-03, -1.47053238e-06,
#         -8.81496820e-03, -1.20960919e-01, -4.21714509e-01, -4.29775301e-01])]

[array([-0.08472077]),
 array([-0.00530241,  0.4078728 ]),
 array([0.03627788, 0.42396549, 0.01832752]),
 array([4.41398935e-02, 4.24895746e-01, 1.93896280e-02, 3.70981852e-05]),
 array([ 4.39572800e-02,  4.24936826e-01,  1.95360434e-02,  4.09593233e-05,
        -1.21859740e-02]),
 array([ 1.05174649e+00,  5.36219341e-01,  1.73618921e-02,  2.53744473e-05,
        -1.17657007e-02, -2.21649954e-01]),
 array([ 9.71711856e-01,  5.21567608e-01,  1.76671678e-02,  1.93844117e-05,
        -1.17596405e-02, -2.01479564e-01, -3.98712430e-02]),
 array([ 7.10267788e-01,  4.47847084e-01,  9.40820722e-03, -1.47053238e-06,
        -8.81496820e-03, -1.20960919e-01, -4.21714509e-01, -4.29775301e-01])]

Now let's see how the first model does scores on the training data.

In [0]:
# Select the first model from the list of models and check the score on the training set here
models[0].score(feature_datasets[0][:training_cutoff], y[:training_cutoff])

# 0.0014673783785782435

0.0014673783785782435

Now loop through all of the models and find the scores on the training datasets.

In [0]:
training_scores = [model.score(feature_dataset[:training_cutoff], y[:training_cutoff]) for model, feature_dataset in zip(models, feature_datasets)]
training_scores
# [0.0014673783785782435,
#  0.45236533768477305,
#  0.4939927242376319,
#  0.4952854616280577,
#  0.4983070309325991,
#  0.5305040120758866,
#  0.535449549407038,
#  0.5844329298051016]

[0.0014673783785782435,
 0.45236533768477294,
 0.4939927242376319,
 0.4952854616280577,
 0.49830703093259904,
 0.5305040120758866,
 0.535449549407038,
 0.5844329298051016]

Next calculate the scores for each model on the holdout dataset.

In [0]:
holdout_scores = [model.score(feature_dataset[training_cutoff:], y[training_cutoff:]) for model, feature_dataset in zip(models, feature_datasets)]

In [0]:
holdout_scores

[-0.035080253443077636,
 0.5290087155979699,
 0.5434340630909423,
 0.542931799661927,
 0.5193319873743076,
 0.53474157472828,
 0.524375220210058,
 0.6605140591532004]

In [0]:
holdout_scores
# [-0.035080253443077636,
#  0.5290087155979699,
#  0.5434340630909426,
#  0.5429317996619257,
#  0.5193319873743043,
#  0.5347415747282829,
#  0.5243752202100567,
#  0.6605140591531988]

[-0.035080253443077636,
 0.5290087155979699,
 0.5434340630909423,
 0.542931799661927,
 0.5193319873743076,
 0.53474157472828,
 0.524375220210058,
 0.6605140591532004]

Ok, now create a trace for the training scores, with the scores on the y axis and the related column on the x axis. 

Do the same for the holdout scores.

In [0]:
# import plotly.graph_objects as go

# model_parameters = ['temps', 'temps + weekends', 'temps + weekends + ages']
# training_trace = go.Scatter(x = model_parameters, y = training_rmses, 
#                               mode = 'lines', 
#                               name = 'training')
# holdout_trace = go.Scatter(x = model_parameters, 
#                              y = holdout_rmses, 
#                              mode = 'lines', name = 'holdout')
# # go.Figure(data = [holdout_trace, training_trace])

In [0]:
import plotly.graph_objects as go

sorted_cols
training_trace = go.Scatter(x = sorted_cols, y = training_scores, 
                              mode = 'lines+markers', 
                              name = 'training')
holdout_trace = go.Scatter(x = sorted_cols, 
                             y = holdout_scores, 
                             mode = 'lines+markers', name = 'holdout')
go.Figure(data = [holdout_trace, training_trace])

> Answer: <img src="https://github.com/jigsawlabs-student/train-test-split/blob/master/8-test-train-split-lab/plotly-graph.png?raw=1" width="80%">

We'll talk more about feature selection in later lessons, but for now, we can see that the holdout score indicates limited benefit by including features like Population, AveOccup, and AveRooms.  Let's try removing these columns, and then see how we do on our training and test datasets.

> Drop the specified columns and assign the resulting dataframe to the variable `X_select`.

In [0]:
X_select = None

In [0]:
X_select[:2]

# MedInc	HouseAge	AveBedrms	Latitude	Longitude
# 0	8.3252	41.0	1.02381	37.88	-122.23
# 1	8.3014	21.0	0.97188	37.86	-122.22

MedInc  HouseAge  AveBedrms  Latitude  Longitude
0  8.3252      41.0    1.02381     37.88    -122.23
1  8.3014      21.0    0.97188     37.86    -122.22

Now let's train one model on these features, just the 80 percent of our training set.

In [0]:
# fit the model on the training data here

# LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

And score the model on the remaining data.

In [0]:

# 0.6710958382245962

0.6710958382245962

### Using SKlearn to Split

Now let's split our data again.  This time, we'll use sklearn's `train_test_split` function.

In [0]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_select, y, test_size = .3, random_state = 1)

In [0]:
model = LinearRegression().fit(X_train, y_train)

In [0]:
model.score(X_test, y_test)

0.5898474184857773