<a href="https://colab.research.google.com/github/ludawg44/jigsawlabs/blob/master/1_numpy_intro_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Intro Lab

### Introduction

In this lesson, let's practice working with the fundamentals of numpy arrays.  This will give us a good foundation when we move onto working with higher dimensional arrays (whatever that is), and the pandas library in the future.

### Creating Arrays

Let's begin by importing the numpy library.

In [0]:
import numpy as np

Next let's use numpy to create a numpy array of even numbers from 2 to 100 and assign this to the variable `even_nums`.

In [0]:
even_nums = None

In [0]:
even_nums = np.array(range(2, 102, 2))
even_nums

# array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
#         28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
#         54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
#         80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

Next, select the first 25 entries in numpy.

In [0]:
first_half_even = even_nums[:25]

In [0]:
len(first_half_even)

# 25

25

### Working with DataTypes

Ok, now let's check the datatype of the numpy array `even_nums`.

In [0]:
even_nums.dtype

# dtype('int64')

dtype('int64')

From our `even_nums` array, use `astype` to create an array of type `float64`, and assign it to the variable `even_floats`.

In [0]:
even_floats = first_half_even

In [0]:
even_floats.astype(np.float64)
# array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24., 26.,
#        28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48., 50.])


array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24., 26.,
       28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48., 50.])

> The decimal point after each number indicates a datatype of float.

Next, let's make a copy of our `even_nums` and change the datatype to type string.

In [0]:
first_half_even.astype(np.str_)

# array(['2', '4', '6', '8', '10', '12', '14', '16', '18', '20', '22', '24',
#        '26', '28', '30', '32', '34', '36', '38', '40', '42', '44', '46',
#        '48', '50'], dtype='<U21')

array(['2', '4', '6', '8', '10', '12', '14', '16', '18', '20', '22', '24',
       '26', '28', '30', '32', '34', '36', '38', '40', '42', '44', '46',
       '48', '50'], dtype='<U21')

> The `U` stands for unicode. Unicode is a information technology standard for the consistent encoding, representation, and handling of text expressed in most of the world's writing systems.  - [Wikipedia](https://en.wikipedia.org/wiki/Unicode)

### Broadcasting 

Now let's move onto working with broadcasting.  Start with `even_nums`, and decrease each item in the array by 1.  Assign the result to the variable `odd_nums`.

In [0]:
odd_nums = even_nums - 1

In [0]:
odd_nums

# array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
#        35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
#        69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

Notice that the original array is unchanged.

In [0]:
even_nums

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

### Adding two arrays

Next, let's see what happens if we add the `even_nums` and `odd_nums` arrays together.

In [0]:
even_nums + odd_nums

# array([  3,   7,  11,  15,  19,  23,  27,  31,  35,  39,  43,  47,  51,
#         55,  59,  63,  67,  71,  75,  79,  83,  87,  91,  95,  99, 103,
#        107, 111, 115, 119, 123, 127, 131, 135, 139, 143, 147, 151, 155,
#        159, 163, 167, 171, 175, 179, 183, 187, 191, 195, 199])

array([  3,   7,  11,  15,  19,  23,  27,  31,  35,  39,  43,  47,  51,
        55,  59,  63,  67,  71,  75,  79,  83,  87,  91,  95,  99, 103,
       107, 111, 115, 119, 123, 127, 131, 135, 139, 143, 147, 151, 155,
       159, 163, 167, 171, 175, 179, 183, 187, 191, 195, 199])

We can see that this performs entrywise addition of the two arrays.  

`[2 + 1, 4 + 3, 6 + 5 ...]`

### Summary

In this lesson, we practiced creating, slicing and broadcasting with numpy arrays.  We also saw to check for and change the datatype in numpy with `dtype` and `astype`.