<a href="https://colab.research.google.com/github/ludawg44/jigsawlabs/blob/master/Copy_of_3_multidimensional_array_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multidimensional Arrays Lab

### Introduction

In this lesson, we'll get started creating and selecting from multidimensional arrays in numpy.  Let's go.

### Creating and Selecting From MultiDimensional Arrays

Let's begin by creating an array with entries 1 through 20, and with four rows and five columns.  Assign it to the variable `one_through_twenty`.

In this lesson, we'll get started working with multidimensional arrays in numpy.  Let's get started.

In [0]:
import numpy as np
one_through_twenty = None

In [0]:
one_through_twenty

# array([[ 1,  2,  3,  4,  5],
#        [ 6,  7,  8,  9, 10],
#        [11, 12, 13, 14, 15],
#        [16, 17, 18, 19, 20]])

Next check that the shape of the array is four rows by five columns.

In [0]:
arr_shape = None

arr_shape
# (4, 5)

### Selecting From a Multidimensional Array

Let's practice selecting elements from a multidimensional array.

In [0]:
one_through_twenty
# array([[ 1,  2,  3,  4,  5],
#        [ 6,  7,  8,  9, 10],
#        [11, 12, 13, 14, 15],
#        [16, 17, 18, 19, 20]])


Begin by selecting the last entry in the first row of the above array.

In [0]:

# 5

5

Next, select the last column in the `one_through_twenty` array.

In [0]:


# array([ 5, 10, 15, 20])

array([ 5, 10, 15, 20])

We can also slice multiple columns in an array.  For example, here we'll slice the first two columns.

In [0]:
one_through_twenty[:, :2]

# array([[ 1,  2],
#        [ 6,  7],
#        [11, 12],
#        [16, 17]])

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

Now it's your turn.  Use a similar pattern to slice the first three rows in the array, and all of the columns.

In [0]:
one_through_twenty[:3, :]

# array([[ 1,  2,  3,  4,  5],
#        [ 6,  7,  8,  9, 10],
#        [11, 12, 13, 14, 15]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

Ok, let's take another look at the full array.

In [0]:
one_through_twenty

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

Next select just the last two entries of the last two rows.

In [0]:
one_through_twenty[-2:, -2:]

# array([[14, 15],
#        [19, 20]])

array([[14, 15],
       [19, 20]])

### Working with Axes

Now that we've practiced creating, and selecting from a multidimensional array, let's practice performing calculations.

We'll start by adding up the rows in our matrix above.

In [0]:
row_sum = None
row_sum
# array([34, 38, 42, 46, 50])

Check that the first item in the returned array is correct by first selecting the first column from `one_through_twenty` and adding all of the items in the column.

In [0]:

# 34

Finally add up all of the items in the `one_through_twenty` array.

In [0]:

# 210

Next let's move onto sorting.

We can create a "random" list of integers between one and twenty like so.

In [0]:
np.random.seed(1)
# seed ensures that the same "random" numbers are returned in the line below each time 

rand_through_twenty = np.random.randint(1, 20, 20).reshape(4, 5)

In [0]:
rand_through_twenty

# array([[ 6, 12, 13,  9, 10],
#        [12,  6, 16,  1, 17],
#        [ 2, 13,  8, 14,  7],
#        [19,  6, 19, 12, 11]])

array([[ 6, 12, 13,  9, 10],
       [12,  6, 16,  1, 17],
       [ 2, 13,  8, 14,  7],
       [19,  6, 19, 12, 11]])

Now use `sort` to have the entries go smallest to largest by row.

In [0]:
# your code here

rand_through_twenty

# array([[ 2,  6,  8,  1,  7],
#        [ 6,  6, 13,  9, 10],
#        [12, 12, 16, 12, 11],
#        [19, 13, 19, 14, 17]])

array([[ 2,  6,  8,  1,  7],
       [ 6,  6, 13,  9, 10],
       [12, 12, 16, 12, 11],
       [19, 13, 19, 14, 17]])

> Notice that unlike the other operations we have seen so far, `sort` **does alter** the original array.

Now sort `rand_through_twenty` by columns.

In [0]:
# your code here

rand_through_twenty

# array([[ 1,  2,  6,  7,  8],
#        [ 6,  6,  9, 10, 13],
#        [11, 12, 12, 12, 16],
#        [13, 14, 17, 19, 19]])

array([[ 1,  2,  6,  7,  8],
       [ 6,  6,  9, 10, 13],
       [11, 12, 12, 12, 16],
       [13, 14, 17, 19, 19]])

Notice that some numbers occur more than once.  Also notice that our entries are not sorted throughout the array.  For example, the number `6` appears in the middle of the first row and in the second row.  Let's use the flatten method to turn `rand_through_twenty` into a one dimension arry, and then sorted that array.

In [0]:
flattened = rand_through_twenty.flatten()

flattened

In [0]:
flattened.sort()

Finally, we can return the array to it's original shape.

In [0]:
flattened.reshape(4, 5)

# array([[ 1,  2,  6,  6,  6],
#        [ 7,  8,  9, 10, 11],
#        [12, 12, 12, 13, 13],
#        [14, 16, 17, 19, 19]])

array([[ 1,  2,  6,  6,  6],
       [ 7,  8,  9, 10, 11],
       [12, 12, 12, 13, 13],
       [14, 16, 17, 19, 19]])

### Summary

In this lesson, we worked with multidimensional arrays in numpy.  We saw how to create new multidimensional arrays by creating a new array from `np.arange` or `np.random.randint`, and then using `reshape` to change the dimensions of the array.  

We then moved onto selecting elements from a multidimensional array using the pattern of row and then column.

Afterwards we saw how we can use our knowledge of `axes` with different numpy methods.  For example, we saw how to `sum` the items across rows, and how to sort our items across rows and then columns (axis 0, and 1 respectively).