<a href="https://colab.research.google.com/github/ludawg44/jigsawlabs/blob/master/Copy_of_2_multidimensional_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multidimensional Numpy Arrays

### Introduction

In the last lesson, we were introduced to numpy arrays.  We saw that unlike lists in Python, with numpy arrays, each item must be of the same type.  We saw that by enforcing a homogenous type, we can perform operations like broadcasting.  

In this lesson, we'll move onto creating and working with multidimensional arrays.

### Creating a Multidimensional Array

Let's begin by starting with a single dimensional array.

In [0]:
import numpy as np
nums_to_twelve = np.arange(1, 13)
nums_to_twelve

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Now let's turn this into an array of two columns.

In [0]:
nums_to_twelve.reshape(6, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

We just used the `reshape` method to create a new array of the same contents but now with `6` rows and `2` columns.  This is typical in numpy: specify the row, then the column.  

Let's try it again, this time with four rows and three columns.

In [0]:
import numpy as np
nums_to_twelve = np.arange(1, 13)

to_twelve_grid = nums_to_twelve.reshape(4, 3)
to_twelve_grid

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

We can see the `shape` of an array with the `shape` method.

In [0]:
to_twelve_grid.shape

(4, 3)

This tells us that there are four rows and three columns in the `to_twelve_grid`.

> Note that we can also view the shape of a single dimensional array.

In [0]:
nums_to_twelve

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [0]:
nums_to_twelve.shape

(12,)

## Selecting with Multidimensional Arrays

Now let's talk about selecting from an array.

Just as **creating** arrays works by specifying the row information followed by the column information, we use the same pattern with **selecting** items.

In [0]:
import numpy as np
nums_to_twelve = np.arange(1, 13)

to_twelve_grid = nums_to_twelve.reshape(4, 3)
to_twelve_grid

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

For example, let's start the last item in the first row.

In [0]:
to_twelve_grid[0, -1]

3

Next let's find the second element in the fourth row.

In [0]:
to_twelve_grid[3, 1]

11

Next, let's select all elements in the first column.

In [0]:
to_twelve_grid[:, 0]

array([ 1,  4,  7, 10])

Well this translates to selecting all the elements in a row, and only the first column.

Next, let's select all of the elements in the second row.  This means we select only the second row, and all of the columns.

In [0]:
to_twelve_grid[1, :]

array([4, 5, 6])

In [0]:
to_twelve_grid

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Understanding an Axis

Let's take another look at our `to_twelve_grid`.  

If this were a plot, we might refer to the items as points in a plot.  Our plot would have a vertical axis, moving down through the rows, and a horizontal axis moving left to right through the columns.  

In numpy the moving downward through the rows is axis 0.  And moving left to right through the columns is axis 1.

In [0]:
to_twelve_grid = nums_to_twelve.reshape(4, 3)
to_twelve_grid

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

We can use this with different operations like sum.  For instance let's add the entries of each row.

In [0]:
np.sum(to_twelve_grid, axis = 0)

array([22, 26, 30])

Let's check to make sure this makes sense.  The first entry is 22 as $1 + 4 + 7 + 10 = 22$.

Now let's add columnwise.

> Here again is our `to_twelve_grid`.

In [0]:
to_twelve_grid

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [0]:
np.sum(to_twelve_grid, axis = 1)

array([ 6, 15, 24, 33])

And if we just wish to sum all of the entries in array we can leave out the `axis` argument.

In [0]:
np.sum(to_twelve_grid)

78

### Summary

In this lesson we learned how to work with multidimensional arrays in numpy.  We saw that our general pattern is to specify `(row, column)`.  We can create a multidimensional array, by calling `reshape` on a one-dimensional array.  And we can select elements from a multidimensional array by specifying the rows items, followed the column items to select.

And we can select an entire row from a matrix, by specifying the row, and then selecting all columns with `:`.

In [0]:
to_twelve_grid

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [0]:
to_twelve_grid[1, :]

array([4, 5, 6])

Then, we learned about an axis in numpy, and that working row-wise (or along the vertical axis) is axis 0, where operating along the columns is axis 1.

So for example if we want to add the entries of all of the we can do so with the following:

In [0]:
np.sum(to_twelve_grid, axis = 0)

array([22, 26, 30])